/*
 * $Id$
 *
 * Copyright (C) 2003-2015 JNode.org
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; If not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package org.jnode.driver.sound.ac97;

import java.util.Collection;

import org.apache.log4j.Logger;
import org.jnode.driver.ApiNotFoundException;
import org.jnode.driver.Device;
import org.jnode.driver.DeviceUtils;
import org.jnode.util.TimeoutException;

/**
 * Static helper for easy access to the AC'97 device(s) of the system. It is
 * the "audio pipeline" entry point: find the driver through the
 * {@link org.jnode.driver.DeviceManager}, then feed raw PCM data into the
 * DMA engine with {@link AC97API#write}.
 *
 * @author JNode contributors
 */
public final class AC97Utils {

    /**
     * My logger
     */
    private static final Logger log = Logger.getLogger(AC97Utils.class);

    private AC97Utils() {
        // static only
    }

    /**
     * Gets the first AC'97 PCM output device of the system, or
     * <code>null</code> if no AC'97 driver is active.
     */
    public static AC97API findDevice() {
        final Collection<Device> devs = DeviceUtils.getDevicesByAPI(AC97API.class);
        if (devs.isEmpty()) {
            return null;
        }
        try {
            return devs.iterator().next().getAPI(AC97API.class);
        } catch (ApiNotFoundException ex) {
            log.debug("No AC'97 API found", ex);
        }
        return null;
    }

    /**
     * Play a tone through the AC'97 DAC, mimicking the API of the
     * {@link org.jnode.driver.sound.speaker.SpeakerAPI} on the PC speaker.
     * <p>
     * The PCM data is generated by {@link ToneGenerator} and pushed through
     * {@link AC97API#write}, which queues it into the buffer descriptor list.
     * Because {@link AC97API#write} blocks while the internal ring buffer is
     * full, this method is rate limited by the hardware and does not need to
     * know anything about interrupts, BDL indices or poll flags.
     *
     * @param frequencyHz tone frequency, 20..10000 Hz
     * @param durationMs  duration in milliseconds
     */
    public static void playTone(int frequencyHz, int durationMs) {
        final AC97API api = findDevice();
        if (api == null) {
            log.error("No AC'97 device found");
            return;
        }
        ToneGenerator generator = null;
        try {
            api.open(AC97Constants.SAMPLE_RATE_48000);
            generator = new ToneGenerator(api.getSampleRate(), frequencyHz,
                durationMs);
            final byte[] chunk = new byte[generator.getFramesPerChunk()
                * AC97Constants.PCM_FRAME_SIZE];
            int count;
            do {
                count = generator.fill(chunk, generator.getFramesPerChunk());
                if (count == 0) {
                    break;
                }
                api.write(chunk, 0, count * AC97Constants.PCM_FRAME_SIZE);
            } while (generator.getRemainingFrames() > 0);
            // Wait until the DAC has actually played every frame we wrote.
            // The engine marks the last descriptor with the buffer underrun
            // policy and halts, so drain() returns on the last sample.
            api.drain();
        } catch (IllegalArgumentException ex) {
            log.error("Invalid tone", ex);
        } catch (InterruptedException ex) {
            // Ignore; the thread was stopped while playing.
        } catch (IllegalStateException ex) {
            log.error("AC'97 playback aborted", ex);
        } catch (TimeoutException ex) {
            log.error("AC'97 DMA engine stalled", ex);
        } finally {
            api.close();
        }
    }
}
